name: Test Project
on:  push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        # with:
        #   path: Code/02\ Basics/03\ Finished\ Project
      - name: Install dependencies 
        run: npm ci
        working-directory: 02-Basics/03-Finished-Project/
      - name: Run tests
        run: npm run test